Configure apt sources

nano /etc/apt/sources.list

# remove all lines and past the following
deb http://ftp.debian.org/debian bookworm main contrib
deb http://ftp.debian.org/debian bookworm-updates main contrib
deb http://security.debian.org/debian-security bookworm-security main contrib
deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

nano /etc/apt/sources.list.d/pve-enterprise.list 
#comment out the following line
deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise